/**
 * i18n validation tests — run with: npx tsx src/i18n/i18n.test.ts
 *
 * Checks:
 * 1. Every supported language has all required namespace files
 * 2. Every JSON file is valid
 * 3. Every language has the same top-level keys as English (reference)
 * 4. No empty translation values
 */
import * as fs from 'fs'
import * as path from 'path'

const LOCALES_DIR = path.join(__dirname, 'locales')

// ── Config: single source of truth ──
const SUPPORTED_LANGS = ['en', 'ko', 'ja', 'zh', 'vi', 'th', 'id', 'es'] as const
const NAMESPACES = [
  'common', 'auth', 'dashboard', 'decks', 'study',
  'marketplace', 'settings', 'history', 'import-export',
  'guide', 'errors', 'paywall', 'update',
  'learning',
] as const

let passed = 0
let failed = 0

function assert(condition: boolean, msg: string) {
  if (condition) {
    passed++
  } else {
    failed++
    console.error(`  FAIL: ${msg}`)
  }
}

// ── Test 1: All locale directories exist ──
console.log('\n[Test 1] Locale directories exist')
for (const lang of SUPPORTED_LANGS) {
  const dir = path.join(LOCALES_DIR, lang)
  assert(fs.existsSync(dir), `Missing locale directory: ${lang}`)
}

// ── Test 2: All namespace files exist and are valid JSON ──
console.log('[Test 2] Namespace files exist and are valid JSON')
for (const lang of SUPPORTED_LANGS) {
  for (const ns of NAMESPACES) {
    const file = path.join(LOCALES_DIR, lang, `${ns}.json`)
    assert(fs.existsSync(file), `Missing: ${lang}/${ns}.json`)
    if (fs.existsSync(file)) {
      try {
        JSON.parse(fs.readFileSync(file, 'utf-8'))
      } catch {
        assert(false, `Invalid JSON: ${lang}/${ns}.json`)
      }
    }
  }
}

// ── Test 3: All languages have same top-level keys as English ──
console.log('[Test 3] Key consistency with English (reference)')
for (const ns of NAMESPACES) {
  const enFile = path.join(LOCALES_DIR, 'en', `${ns}.json`)
  if (!fs.existsSync(enFile)) continue
  const enKeys = Object.keys(JSON.parse(fs.readFileSync(enFile, 'utf-8'))).sort()

  for (const lang of SUPPORTED_LANGS) {
    if (lang === 'en') continue
    const file = path.join(LOCALES_DIR, lang, `${ns}.json`)
    if (!fs.existsSync(file)) continue
    const langKeys = Object.keys(JSON.parse(fs.readFileSync(file, 'utf-8'))).sort()

    const missing = enKeys.filter((k) => !langKeys.includes(k))
    assert(
      missing.length === 0,
      `${lang}/${ns}.json missing keys: ${missing.join(', ')}`,
    )
  }
}

// ── Test 4: No empty string values (top level) ──
console.log('[Test 4] No empty translation values')
for (const lang of SUPPORTED_LANGS) {
  for (const ns of NAMESPACES) {
    const file = path.join(LOCALES_DIR, lang, `${ns}.json`)
    if (!fs.existsSync(file)) continue
    const data = JSON.parse(fs.readFileSync(file, 'utf-8'))
    const emptyKeys = Object.entries(data)
      .filter(([, v]) => typeof v === 'string' && v.trim() === '')
      .map(([k]) => k)
    assert(
      emptyKeys.length === 0,
      `${lang}/${ns}.json has empty values: ${emptyKeys.join(', ')}`,
    )
  }
}

// ── Test 5: every {{x, <fmt>}} spec used in a locale has an Intl-free override ──
// i18next's built-in formatters go through Intl, which silently drops thousands separators
// on a Hermes build without full ICU. src/i18n/index.ts overrides `number` for that reason;
// this guards both directions — the override must not disappear while locales rely on it,
// and a NEW format spec must not be introduced without an override.
console.log('[Test 5] Locale format specs have Intl-free overrides')
{
  const specs = new Set<string>()
  for (const lang of SUPPORTED_LANGS) {
    for (const ns of NAMESPACES) {
      const file = path.join(LOCALES_DIR, lang, `${ns}.json`)
      if (!fs.existsSync(file)) continue
      const raw = fs.readFileSync(file, 'utf-8')
      for (const m of raw.matchAll(/\{\{\s*[a-zA-Z0-9_]+\s*,\s*([a-zA-Z]+)/g)) specs.add(m[1])
    }
  }
  const config = fs.readFileSync(path.join(__dirname, 'index.ts'), 'utf-8')
  for (const spec of specs) {
    assert(
      new RegExp(`formatter\\??\\.add\\(\\s*['"\`]${spec}['"\`]`).test(config),
      `locales use {{x, ${spec}}} but src/i18n/index.ts registers no Intl-free '${spec}' formatter ` +
        `— on a Hermes build without full ICU it would silently drop separators`,
    )
  }
}

// ── Test 6: every learning key the SCREENS can request actually exists ─────────
//
// Why this test exists: `today.error.*` and `goals.error.*` were missing from all eight
// mobile bundles while every screen shipped, and nothing caught it. Test 3 compares only
// TOP-LEVEL keys, and the bundles were generated by extracting literal `t('...')` calls —
// but these keys are produced by `errorKey(code)`, which returns a string from a switch.
// A learner who hit the plan cap was shown the literal text `today.error.limitExceeded`.
//
// So the extractor here does NOT look for `t(...)`. It collects every dotted string literal
// in the learning screens, which catches a key wherever it is written — inside `t()`, in a
// `return` of a mapper, or in a lookup table. Template-interpolated families cannot be read
// from source, so they are enumerated below and that list is the price of computing a key.
console.log('[Test 6] Learning screens: every requestable key exists in every locale')
{
  const SCREENS_DIR = path.join(__dirname, '..', 'screens')
  const learningScreens = fs.existsSync(SCREENS_DIR)
    ? fs.readdirSync(SCREENS_DIR).filter((f) => /^Learning.*\.tsx$/.test(f))
    : []
  assert(learningScreens.length > 0, 'no Learning*.tsx screens found — extractor would pass vacuously')

  const enLearning = JSON.parse(
    fs.readFileSync(path.join(LOCALES_DIR, 'en', 'learning.json'), 'utf-8'),
  ) as Record<string, unknown>
  // Only assert keys in the learning namespace; the screens also read `common`.
  const roots = new Set(Object.keys(enLearning))

  const required = new Set<string>()
  for (const file of learningScreens) {
    const src = fs.readFileSync(path.join(SCREENS_DIR, file), 'utf-8')
    for (const m of src.matchAll(/['"]([a-z][a-zA-Z0-9]*(?:\.[a-zA-Z0-9_]+)+)['"]/g)) {
      const key = m[1]
      if (roots.has(key.split('.')[0])) required.add(key)
    }
  }

  // Families built by interpolation — `t(`recommend.status.${rec.status}`)` and friends.
  // Each list must hold every value the corresponding column/enum can take.
  const FAMILIES: Record<string, readonly string[]> = {
    'recommend.status': ['accepted', 'dismissed', 'expired'],
    'goals.status': ['paused', 'completed', 'archived'],
    'form.domainName': ['language', 'labor-law'],
    'enrichment.error': [
      'INSUFFICIENT_CREDITS', 'RATE_CAP', 'GROUNDING_REQUIRED', 'INVALID_RESULT',
      'PROVIDER_ERROR', 'BAD_REQUEST', 'NETWORK', 'UNKNOWN',
    ],
    'today.reason': [
      'due', 'memoryRisk', 'recentFailure', 'slowResponse', 'goalRelevance', 'importance', 'balanced',
    ],
  }
  for (const [prefix, values] of Object.entries(FAMILIES)) {
    for (const value of values) required.add(`${prefix}.${value}`)
  }

  const lookup = (data: Record<string, unknown>, key: string): unknown => {
    let cur: unknown = data
    for (const part of key.split('.')) {
      if (typeof cur !== 'object' || cur === null || !(part in (cur as object))) return undefined
      cur = (cur as Record<string, unknown>)[part]
    }
    return cur
  }

  for (const lang of SUPPORTED_LANGS) {
    const data = JSON.parse(
      fs.readFileSync(path.join(LOCALES_DIR, lang, 'learning.json'), 'utf-8'),
    ) as Record<string, unknown>
    const missing = [...required].filter((key) => typeof lookup(data, key) !== 'string').sort()
    assert(
      missing.length === 0,
      `${lang}/learning.json is missing ${missing.length} key(s) the screens can request: ` +
        `${missing.slice(0, 8).join(', ')}${missing.length > 8 ? ' …' : ''}`,
    )
  }
}

// ── Test 7: the resource bundle and the namespace list agree ─────────────────
//
// Why this test exists: `learning` was listed in `ns: [...]` but never added to `resources`.
// i18next's answer to a namespace it has no data for is to echo the key, so all three
// learning screens rendered "insights.title" and "today.empty.noGoal" as visible text — on
// the real simulator, in production, via OTA. Tests 1–6 all passed: the locale FILES were
// perfect, they were simply never loaded.
//
// The `ns → resources` direction is the dangerous one and is asserted as a hard failure. The
// reverse (a bundled namespace missing from `ns`) only skips preloading, so it is reported
// but not fatal.
console.log('[Test 7] i18n resources actually contain every declared namespace')
{
  const config = fs.readFileSync(path.join(__dirname, 'index.ts'), 'utf-8')

  const nsMatch = config.match(/\bns:\s*\[([^\]]*)\]/)
  assert(!!nsMatch, "could not find the `ns: [...]` list in src/i18n/index.ts")
  const declared = nsMatch
    ? [...nsMatch[1].matchAll(/['"]([^'"]+)['"]/g)].map((m) => m[1])
    : []
  assert(declared.length > 0, '`ns: [...]` parsed as empty — the check would pass vacuously')

  for (const ns of declared) {
    for (const lang of SUPPORTED_LANGS) {
      // The literal require the bundler needs; a dynamic path would not be bundled at all.
      const needle = `./locales/${lang}/${ns}.json`
      assert(
        config.includes(needle),
        `namespace '${ns}' is declared in ns[] but src/i18n/index.ts never requires ` +
          `'${needle}' — every key in it would render as its own name`,
      )
    }
  }

  // Files present and loaded but not declared: harmless, still worth surfacing.
  const bundled = new Set(
    [...config.matchAll(/\.\/locales\/en\/([a-zA-Z-]+)\.json/g)].map((m) => m[1]),
  )
  const undeclared = [...bundled].filter((ns) => !declared.includes(ns))
  if (undeclared.length > 0) {
    console.log(`  NOTE: bundled but not in ns[]: ${undeclared.join(', ')} (preload skipped only)`)
  }
}

// ── Test 8: count-interpolated keys have plural forms where the language needs them ──
//
// Why this test exists: the goals list rendered "1 decks" on a real device. `{{count}}` on
// its own does not make a string plural-aware — i18next needs `key_one` / `key_other`, and
// without them English gets the plural noun at every count.
//
// Unit abbreviations ("20 min/day", "3s") do not inflect, so they are listed as invariant
// rather than silently skipped: adding a new counted noun forces a decision here.
console.log('[Test 8] Counted strings inflect in languages that inflect')
{
  const PLURAL_LANGS = ['en', 'es'] as const
  const INVARIANT = new Set([
    'goals.dailyMinutes',  // "20 min/day" — abbreviation, no plural form
    'today.budget',        // same string, same reason
    'insights.seconds',    // "3s"
    'today.item.minutes',  // "~3 min" — abbreviation, and the web copy uses the same form
  ])

  const SCREENS_DIR = path.join(__dirname, '..', 'screens')
  const counted = new Set<string>()
  if (fs.existsSync(SCREENS_DIR)) {
    for (const file of fs.readdirSync(SCREENS_DIR).filter((f) => /^Learning.*\.tsx$/.test(f))) {
      const src = fs.readFileSync(path.join(SCREENS_DIR, file), 'utf-8')
      for (const m of src.matchAll(/t\(\s*['"]([a-zA-Z0-9_.]+)['"]\s*,\s*\{[^}]*\bcount\b/g)) {
        counted.add(m[1])
      }
    }
  }
  assert(counted.size > 0, 'no counted keys found — the check would pass vacuously')

  const lookup = (data: Record<string, unknown>, key: string): unknown => {
    let cur: unknown = data
    for (const part of key.split('.')) {
      if (typeof cur !== 'object' || cur === null || !(part in (cur as object))) return undefined
      cur = (cur as Record<string, unknown>)[part]
    }
    return cur
  }

  for (const lang of PLURAL_LANGS) {
    const data = JSON.parse(
      fs.readFileSync(path.join(LOCALES_DIR, lang, 'learning.json'), 'utf-8'),
    ) as Record<string, unknown>
    for (const key of counted) {
      if (INVARIANT.has(key)) continue
      const one = lookup(data, `${key}_one`)
      const other = lookup(data, `${key}_other`)
      assert(
        typeof one === 'string' && typeof other === 'string',
        `${lang}/learning.json: '${key}' is used with a count but has no _one/_other forms — ` +
          `it would read "1 <plural>". Add both, or list the key as INVARIANT if it is a unit.`,
      )
    }
  }
}

// ── Summary ──
console.log(`\n✅ Passed: ${passed}`)
if (failed > 0) {
  console.log(`❌ Failed: ${failed}`)
  process.exit(1)
} else {
  console.log('All i18n tests passed!')
}
