import { describe, it, expect } from 'vitest'
import { generateInviteCode, validateInviteCode } from '../invite'

describe('generateInviteCode', () => {
  it('should return an 8-character string', () => {
    const code = generateInviteCode()
    expect(code).toHaveLength(8)
  })

  it('should only contain alphanumeric characters', () => {
    for (let i = 0; i < 20; i++) {
      const code = generateInviteCode()
      expect(code).toMatch(/^[A-Za-z0-9]{8}$/)
    }
  })

  it('should generate unique codes', () => {
    const codes = new Set<string>()
    for (let i = 0; i < 100; i++) {
      codes.add(generateInviteCode())
    }
    expect(codes.size).toBe(100)
  })
})

describe('validateInviteCode', () => {
  it('should accept valid 8-char alphanumeric codes', () => {
    expect(validateInviteCode('AbCd1234')).toBe(true)
    expect(validateInviteCode('ZZZZZZZZ')).toBe(true)
    expect(validateInviteCode('00000000')).toBe(true)
  })

  it('should reject codes that are too short', () => {
    expect(validateInviteCode('abc')).toBe(false)
    expect(validateInviteCode('')).toBe(false)
  })

  it('should reject codes that are too long', () => {
    expect(validateInviteCode('AbCd12345')).toBe(false)
  })

  it('should reject codes with special characters', () => {
    expect(validateInviteCode('abc-1234')).toBe(false)
    expect(validateInviteCode('abc_1234')).toBe(false)
    expect(validateInviteCode('abc 1234')).toBe(false)
  })

  it('should validate codes generated by generateInviteCode', () => {
    for (let i = 0; i < 20; i++) {
      const code = generateInviteCode()
      expect(validateInviteCode(code)).toBe(true)
    }
  })
})
